CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'btekinli'@'%' IDENTIFIED BY 'force99';
GRANT ALL PRIVILEGES ON wordpress.* TO 'btekinli'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'rootforce99';
